2025-01-20 22:29:31,609 | INFO | "test_challenge" выполнен успешно
2025-01-20 22:29:31,610 | WARNING | Неверное имя для Runner
2025-01-20 22:29:31,610 | WARNING | Traceback (most recent call last):
  File "C:\Users\nata_\PycharmProjects\Homework_block12\tests_12_4.py", line 35, in test_run
    runner = runner_plus_file.Runner( 6754 , 5)
  File "C:\Users\nata_\PycharmProjects\Homework_block12\runner_plus_file.py", line 7, in __init__
    raise ValueError(f'Имя может быть только строкой, передано {type(name).__name__}')
ValueError: Имя может быть только строкой, передано int

2025-01-20 22:29:31,610 | WARNING | Неверная скорость для Runner
2025-01-20 22:29:31,611 | WARNING | Traceback (most recent call last):
  File "C:\Users\nata_\PycharmProjects\Homework_block12\tests_12_4.py", line 20, in test_walk
    runner = runner_plus_file.Runner('Walker', -5)
  File "C:\Users\nata_\PycharmProjects\Homework_block12\runner_plus_file.py", line 12, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5

